spring:
  application:
    name: anime-quotes
  datasource:
    url: jdbc:postgresql://localhost:5432/anime_quotes
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    database: POSTGRESQL
